Lesson list branch
Pithia-2/pithia-2 pull request #62
Opened 2019-11-13 15:52 UTC by Kostasssss

2019-11-13 16:08 UTC, FeedMyCat54 requested changes
please remove the button from the student info page and use the button in the home page as i instructed.

2019-11-13 16:23 UTC, FeedMyCat54 requested changes
The department dropdown does not function. Furthmore the back button does not function either. Moreover the home and the sign out buttons should be removed from the page as they serve no purpose and do not work either.

2019-11-13 18:29 UTC, CrazyStevenz requested changes
Create button listener was erroneously deleted, please re-add it.

2019-11-13 18:35 UTC, FeedMyCat54 submitted a review, later dismissed

2019-11-14 11:16 UTC, CrazyStevenz approved these changes

2019-11-14 11:16 UTC, FeedMyCat54 approved these changes

2019-11-14 11:16 UTC, merged